### ISSUE TITLE
Is it possible to create a PDF file with index?

### ISSUE THREAD

**Issue by joffrey-bion** [rekka/tectonic-docker#2]
I'm not familiar at all with tectonic itself, but I didn't find a way to generate the index.
Running tectonic does generate a `.idx` file, but the PDF does not have the index section.

It is mentioned in [this issue](https://github.com/tectonic-typesetting/tectonic/issues/115) that we can run tectonic + makeindex + tectonic again as a workaround, but I couldn't manage to run `makeindex` from this docker image. 
Is it present in the image? Did I just miss it?

**Comment by rekka** [comment]
Sorry about the late response. 

The docker image is supposed to be minimal for my personal purposes with only tectonic itself. That said, you can use it as a base image and add makeindex to it. I do not have experience with makeindex, but if it is a simple binary, you can probably just install makeindex in the usual way (I guess via texlive), and then copy only the binary over to the final docker image.

**Comment by joffrey-bion** [comment]
Actually, it was unnecessary for me to use makeindex from the docker image itself. I ended up configuring my 
Travis build to install makeindex in the Travis context as part of the texlive-binaries package. I then used tectonic-docker simply as a tectonic binary:

```yaml
sudo: required
services: docker

before_install:
# installs makeindex
- sudo apt-get install texlive-binaries

script:
# we use the docker image from https://hub.docker.com/r/rekka/tectonic/
- docker pull rekka/tectonic
# first run to generate index data
- docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind rekka/tectonic tectonic songs.tex
- makeindex src/songs.idx
# second run to generate the final PDF with the index (.idx file has to be next to the tex file)
- docker run --mount src=$TRAVIS_BUILD_DIR/src,target=/usr/src/tex,type=bind rekka/tectonic tectonic songs.tex
```
